language: python
python:
    - "3.3"
    - "3.4"
    - "3.5"

install:
    - python3 setup.py install
    - pip install pytest pytest-cov coveralls

script:
    - py.test tests -v --cov includer --cov-report term-missing

after_success:
    - coveralls
